services:
  bot:
    container_name: discord-bot
    image: ghcr.io/baymesh/rage-against-the-meshine-nextgen:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - REDIS_URL=${REDIS_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - web
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./src
          target: /app/src
          action: sync
        - path: ./tsconfig.json
          target: /app/tsconfig.json
          action: sync
networks:
  web:
    external: true
